---
- name: group module demo
  hosts: all
  become: true
  vars:
    mygroup: "supergroup"
    user2: "user2"
    user3: "user3"
    userpass2: "user_password2"
    userpass3: "user_password3"
  tasks:
    - name: create group
      ansible.builtin.group:
        name: "{{ mygroup }}"
        state: present
    - name: create user 2
      ansible.builtin.user:
        name: "{{ user2 }}"
        shell: /bin/bash
        groups: supergroup
        state: present
        password: "{{ userpass2 | password_hash('sha512') }}"
        update_password: on_create
    - name: create user 3
      ansible.builtin.user:
        name: "{{ user3 }}"
        shell: /bin/bash
        groups: supergroup
        state: present
        password: "{{ userpass3 | password_hash('sha512') }}"
    - name: enable passwordless sudo for supergroup
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%"{{ mygroup}}"'
        line: '"{{ mygroup }}" ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
